if(CMAKE_SIZEOF_VOID_P EQUAL 8)
  execute_process(
    COMMAND
      "${CMAKE_COMMAND}" -S ${CMAKE_CURRENT_SOURCE_DIR} -B ${CMAKE_SOURCE_DIR}/build_x86 -A Win32 -G
      "${CMAKE_GENERATOR}" -DCMAKE_SYSTEM_VERSION:STRING='${CMAKE_SYSTEM_VERSION}'
      -DVIRTUALCAM_GUID:STRING=${VIRTUALCAM_GUID} -DCMAKE_MESSAGE_LOG_LEVEL=${CMAKE_MESSAGE_LOG_LEVEL}
      -DENABLE_CCACHE=${ENABLE_CCACHE}
    RESULT_VARIABLE _process_result COMMAND_ERROR_IS_FATAL ANY)
endif()